### PR TITLE
Regulation modal

### PR DESCRIPTION
**Pull request by alexey-klimuk**
**Merge BACKEND app first!**

Desktop view:
screenshot from 2017-12-08 14-16-43

Mobile view:
image1 1

### CODE REVIEW

**Comment by alexey-klimuk** [comment]
[[TARIFF17] Improve lookup of legal notices](https://trello.com/c/kYHAA4qt/2028-tariff17-improve-lookup-of-legal-notices)

**Comment by alexey-klimuk** [comment]
@matthewford table is scrollable now

**Comment by matthewford** [comment]
@alexey-klimuk yeah scrolling won't really help as users might not see it, lets make the reg number in the popup also a link:

screen shot 2017-12-08 at 15 12 41

**Comment by alexey-klimuk** [comment]
@matthewford done :white_check_mark:

**Pull request merged**
