### PR TITLE
Search as post

### PR DESCRIPTION
**Pull request by theharq**
This PR changes the search endpoint to expect a `POST` request instead of a `GET`

#### Notes

It also refactors the snippet of FullStory so this is ran only in production and the code related is in one place only.

### CODE REVIEW

**Comment by theharq** [comment]
[[TARIFF16] Odd issues with country selection](https://trello.com/c/xDOXRaPc/1348-tariff16-odd-issues-with-country-selection)

**Comment by matthewford** [comment]
@theharq can we hide the FS code for now?

**Comment by theharq** [comment]
sure I will not render the `fullstory_snippet` partial 👍

**Comment by theharq** [comment]
PR updated.. now the FullStory code is never rendered.

**Pull request merged**
