### PR TITLE
Custom errors pages

### PR DESCRIPTION
**Pull request by theharq**
#### What this PR does:

- Adds custom error pages.

#### Notes

I've removed some config related to ports and hosts. Instructions for starting all tariff apps locally are here: https://github.com/bitzesty/trade-tariff-cf

The `slimmer` gem was used before but this commit https://github.com/bitzesty/trade-tariff-frontend/commit/0743049f6c7896fce613a66b599007063102e85f remove this gem in favor of `govuk_template` gem.

so instead adding this gem again, I took the copy from their 404 and 500 pages.

It's worth mentioning that this gem (slimmer) has a different footer than govuk_template.. is not worth to install this gem with all the changes that may occur for just displaying customised error pages.

### CODE REVIEW

**Comment by theharq** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;vVe0xQH1&#x2F;136-tariff16-error-pages"> [TARIFF16] Error pages</a>

**Comment by matthewford** [comment]
@theharq we will be customising the footer anyway

**Comment by matthewford** [comment]
@theharq can we keep the .env and .foreman files, someone might want to just run without running from the cf repo.

**Comment by matthewford** [comment]
@theharq ^

**Comment by theharq** [comment]
Updated

**Pull request merged**
